FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

COPY target/*.jar app.jar

RUN mkdir -p /app/uploads
VOLUME /app/uploads

ENV SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/profile?useSSL=false&serverTimezone=UTC
ENV UPLOAD_PATH=/app/uploads/

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
